name: Build and Run Ray Tracer (Windows)

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build solution
      run: msbuild YourProject.sln /p:Configuration=Release

    - name: Run ray tracer
      run: .\Release\YourExecutable.exe
